CREATE TABLE users (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cert BINARY(20) NOT NULL UNIQUE,
	name VARCHAR(255) NOT NULL
);

CREATE TABLE user_perm (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id BIGINT UNSIGNED NOT NULL,
	module VARCHAR(255) NOT NULL,
	action VARCHAR(255) NOT NULL,
	param VARCHAR(255) NOT NULL,
	KEY user_id (user_id),
	CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE list_perm (
	module VARCHAR(63) NOT NULL,
	action VARCHAR(63) NOT NULL,
	param VARCHAR(63) NOT NULL,
	KEY perm (module, action, param)
);
